"""Hupy 60-planet curriculum content.

Canonical content for the course expansion (planets 9-60). Each planet
carries:

  number  -> 1..60
  titles  -> (en, pt, es) planet name / theme
  subs    -> (en, pt, es) subtitle in "Theme — communication goal" form
  topics  -> (3 short topic strings)
  sentences -> 4 key sentences, each (en, pt, es, subject, verb, complement)
               where subject/verb/complement describe the English sentence.

Planets 1-8 already exist (with rich sentence banks) — only their level/goal
is backfilled by the generator. Levels by number: 1-10 A1, 11-20 A2, 21-30
B1, 31-40 B2, 41-50 B2+, 51-60 C1. Colors are assigned by the generator.
"""


def S(en, pt, es, subject="", verb="", complement=""):
    return (en, pt, es, subject, verb, complement)


# number, titles(en,pt,es), subs(en,pt,es), topics, sentences
PLANETS = [
    (
        9,
        ("Places and Directions", "Lugares e direções", "Lugares y direcciones"),
        ("Places and Directions — ask for and understand directions, find places in town",
         "Lugares e Direções — pergunte e entenda direções, encontre lugares na cidade",
         "Lugares y Direcciones — pregunta y entiende direcciones, encuentra lugares en la ciudad"),
        ("Asking for directions", "Places in town", "Getting around"),
        [
            S("Where is the supermarket, please?", "Onde fica o supermercado, por favor?", "¿Dónde está el supermercado, por favor?", "the supermarket", "is", "where"),
            S("Go straight and turn left.", "Vá em frente e vire à esquerda.", "Ve recto y gira a la izquierda.", "you", "go", "straight and turn left"),
            S("The bank is next to the pharmacy.", "O banco fica ao lado da farmácia.", "El banco está al lado de la farmacia.", "the bank", "is", "next to the pharmacy"),
            S("Is it far from here?", "É longe daqui?", "¿Está lejos de aquí?", "it", "is", "far from here"),
        ],
    ),
    (
        10,
        ("Review & A1 Mission", "Revisão e missão prática A1", "Repaso y misión práctica A1"),
        ("Review & A1 Mission — put everything together in one complete conversation",
         "Revisão e Missão A1 — junte tudo em uma conversa completa",
         "Repaso y Misión A1 — únelo todo en una conversación completa"),
        ("Full conversation", "Review", "A1 mission"),
        [
            S("Good morning! How are you today?", "Bom dia! Como você está hoje?", "¡Buenos días! ¿Cómo estás hoy?", "you", "are", "how today"),
            S("My name is Ana and I am from Brazil.", "Meu nome é Ana e eu sou do Brasil.", "Me llamo Ana y soy de Brasil.", "I", "am", "from Brazil"),
            S("I have a brother and two sisters.", "Eu tenho um irmão e duas irmãs.", "Tengo un hermano y dos hermanas.", "I", "have", "a brother and two sisters"),
            S("I go to work every day.", "Eu vou trabalhar todos os dias.", "Voy a trabajar todos los días.", "I", "go", "to work every day"),
        ],
    ),
    (
        11,
        ("Home and Chores", "Casa e tarefas domésticas", "Casa y tareas del hogar"),
        ("Home and Chores — describe your home, divide and report everyday tasks",
         "Casa e Tarefas — descreva sua casa, divida e relate tarefas do dia a dia",
         "Casa y Tareas — describe tu casa, divide y cuenta las tareas diarias"),
        ("Around the house", "Chores", "Sharing tasks"),
        [
            S("I do the dishes after dinner.", "Eu lavo a louça depois do jantar.", "Lavo los platos después de la cena.", "I", "do", "the dishes after dinner"),
            S("She is cleaning the kitchen now.", "Ela está limpando a cozinha agora.", "Ella está limpiando la cocina ahora.", "she", "is cleaning", "the kitchen now"),
            S("Can you take out the trash, please?", "Você pode levar o lixo para fora, por favor?", "¿Puedes sacar la basura, por favor?", "you", "can take", "out the trash"),
            S("We usually do the laundry on weekends.", "Nós geralmente lavamos a roupa nos fins de semana.", "Normalmente lavamos la ropa los fines de semana.", "we", "do", "the laundry on weekends"),
        ],
    ),
    (
        12,
        ("Work and Professions", "Trabalho e profissões", "Trabajo y profesiones"),
        ("Work and Professions — talk about your job, duties and work history",
         "Trabalho e Profissões — fale sobre seu trabalho, funções e histórico",
         "Trabajo y Profesiones — habla de tu trabajo, funciones e historial"),
        ("Jobs", "Duties", "Work history"),
        [
            S("I work as a nurse in a hospital.", "Eu trabalho como enfermeira em um hospital.", "Trabajo como enfermera en un hospital.", "I", "work", "as a nurse in a hospital"),
            S("What do you do for a living?", "O que você faz da vida?", "¿A qué te dedicas?", "you", "do", "for a living"),
            S("She works from home three days a week.", "Ela trabalha de casa três dias por semana.", "Ella trabaja desde casa tres días a la semana.", "she", "works", "from home three days a week"),
            S("I started this job last year.", "Comecei este trabalho no ano passado.", "Empecé este trabajo el año pasado.", "I", "started", "this job last year"),
        ],
    ),
    (
        13,
        ("School and Learning", "Escola e aprendizagem", "Escuela y aprendizaje"),
        ("School and Learning — talk about classes, teachers and your studies",
         "Escola e Aprendizagem — fale sobre aulas, professores e seus estudos",
         "Escuela y Aprendizaje — habla de clases, profesores y tus estudios"),
        ("Classes", "Teachers", "Learning goals"),
        [
            S("I am learning English at night school.", "Estou aprendendo inglês na escola noturna.", "Estoy aprendiendo inglés en la escuela nocturna.", "I", "am learning", "English at night school"),
            S("The teacher explained the lesson very well.", "A professora explicou a lição muito bem.", "La profesora explicó la lección muy bien.", "the teacher", "explained", "the lesson very well"),
            S("Did you do your homework?", "Você fez sua lição de casa?", "¿Hiciste tu tarea?", "you", "did", "your homework"),
            S("I want to speak English fluently.", "Quero falar inglês fluentemente.", "Quiero hablar inglés con fluidez.", "I", "want", "to speak English fluently"),
        ],
    ),
    (
        14,
        ("Health and Body", "Saúde e corpo", "Salud y cuerpo"),
        ("Health and Body — describe symptoms, get advice and talk about habits",
         "Saúde e Corpo — descreva sintomas, peça conselhos e fale de hábitos",
         "Salud y Cuerpo — describe síntomas, pide consejos y habla de hábitos"),
        ("Symptoms", "At the doctor", "Healthy habits"),
        [
            S("I have a headache and a sore throat.", "Estou com dor de cabeça e dor de garganta.", "Tengo dolor de cabeza y dolor de garganta.", "I", "have", "a headache and a sore throat"),
            S("You should drink more water.", "Você deveria beber mais água.", "Deberías beber más agua.", "you", "should drink", "more water"),
            S("I went to the doctor yesterday.", "Fui ao médico ontem.", "Fui al médico ayer.", "I", "went", "to the doctor yesterday"),
            S("How often do you exercise?", "Com que frequência você se exercita?", "¿Con qué frecuencia haces ejercicio?", "you", "exercise", "how often"),
        ],
    ),
    (
        15,
        ("Transport and Getting Around", "Transporte e deslocamento", "Transporte y desplazamiento"),
        ("Transport and Getting Around — use public transport, compare times and routes",
         "Transporte e Deslocamento — use transporte público, compare horários e rotas",
         "Transporte y Desplazamiento — usa transporte público, compara horarios y rutas"),
        ("Public transport", "Times and routes", "Commuting"),
        [
            S("I usually take the subway to work.", "Geralmente pego o metrô para ir ao trabalho.", "Normalmente tomo el metro para ir al trabajo.", "I", "take", "the subway to work"),
            S("The bus was crowded this morning.", "O ônibus estava lotado esta manhã.", "El autobús estaba lleno esta mañana.", "the bus", "was", "crowded this morning"),
            S("How long does it take to get downtown?", "Quanto tempo leva para chegar ao centro?", "¿Cuánto tarda en llegar al centro?", "it", "takes", "how long to get downtown"),
            S("We missed our train by five minutes.", "Perdemos nosso trem por cinco minutos.", "Perdimos nuestro tren por cinco minutos.", "we", "missed", "our train by five minutes"),
        ],
    ),
    (
        16,
        ("Travel and Accommodation", "Viagens e hospedagem", "Viajes y alojamiento"),
        ("Travel and Accommodation — book rooms, check in and ask for services",
         "Viagens e Hospedagem — reserve quartos, faça check-in e peça serviços",
         "Viajes y Alojamiento — reserva habitaciones, haz el check-in y pide servicios"),
        ("Hotels", "Booking", "Travel services"),
        [
            S("I booked a room near the beach.", "Reservei um quarto perto da praia.", "Reservé una habitación cerca de la playa.", "I", "booked", "a room near the beach"),
            S("The hotel has a swimming pool and a restaurant.", "O hotel tem piscina e restaurante.", "El hotel tiene piscina y restaurante.", "the hotel", "has", "a swimming pool and a restaurant"),
            S("Could I have a wake-up call at seven, please?", "Você poderia me acordar às sete, por favor?", "¿Podría darme una llamada de despertador a las siete, por favor?", "I", "could have", "a wake-up call at seven"),
            S("We checked in at two in the afternoon.", "Fizemos o check-in às duas da tarde.", "Hicimos el check-in a las dos de la tarde.", "we", "checked in", "at two in the afternoon"),
        ],
    ),
    (
        17,
        ("Past Experiences", "Experiências passadas", "Experiencias pasadas"),
        ("Past Experiences — tell what happened, when and how you felt",
         "Experiências Passadas — conte o que aconteceu, quando e como você se sentiu",
         "Experiencias Pasadas — cuenta qué pasó, cuándo y cómo te sentiste"),
        ("Past events", "Telling what happened", "Feelings"),
        [
            S("I visited my grandparents last weekend.", "Visitei meus avós no último fim de semana.", "Visité a mis abuelos el fin de semana pasado.", "I", "visited", "my grandparents last weekend"),
            S("Did you enjoy the concert?", "Você gostou do show?", "¿Disfrutaste del concierto?", "you", "enjoyed", "the concert"),
            S("We watched a movie and ordered pizza.", "Assistimos a um filme e pedimos pizza.", "Vimos una película y pedimos pizza.", "we", "watched", "a movie and ordered pizza"),
            S("She lived in London for two years.", "Ela morou em Londres por dois anos.", "Ella vivió en Londres durante dos años.", "she", "lived", "in London for two years"),
        ],
    ),
    (
        18,
        ("Future Plans and Intentions", "Planos e intenções futuras", "Planes e intenciones futuras"),
        ("Future Plans and Intentions — talk about plans, promises and intentions",
         "Planos e Intenções Futuras — fale sobre planos, promessas e intenções",
         "Planes e Intenciones Futuras — habla de planes, promesas e intenciones"),
        ("Plans", "Going to", "Will"),
        [
            S("I am going to visit my family next month.", "Vou visitar minha família no próximo mês.", "Voy a visitar a mi familia el próximo mes.", "I", "am going to visit", "my family next month"),
            S("Are you going to come to the party?", "Você vai vir à festa?", "¿Vas a venir a la fiesta?", "you", "are going to come", "to the party"),
            S("I will call you when I arrive.", "Vou te ligar quando chegar.", "Te llamaré cuando llegue.", "I", "will call", "you when I arrive"),
            S("We are going to travel to Portugal in July.", "Nós vamos viajar para Portugal em julho.", "Vamos a viajar a Portugal en julio.", "we", "are going to travel", "to Portugal in July"),
        ],
    ),
    (
        19,
        ("Problems and Asking for Help", "Problemas e pedidos de ajuda", "Problemas y pedidos de ayuda"),
        ("Problems and Asking for Help — report problems and ask for help politely",
         "Problemas e Pedidos de Ajuda — relate problemas e peça ajuda com educação",
         "Problemas y Pedidos de Ayuda — cuenta problemas y pide ayuda con educación"),
        ("Reporting problems", "Asking for help", "Reassurance"),
        [
            S("I have a problem with my phone.", "Tenho um problema com meu celular.", "Tengo un problema con mi teléfono.", "I", "have", "a problem with my phone"),
            S("Could you help me, please?", "Você poderia me ajudar, por favor?", "¿Podrías ayudarme, por favor?", "you", "could help", "me"),
            S("I lost my wallet in the taxi.", "Perdi minha carteira no táxi.", "Perdí mi cartera en el taxi.", "I", "lost", "my wallet in the taxi"),
            S("Don't worry, everything will be fine.", "Não se preocupe, tudo vai ficar bem.", "No te preocupes, todo va a estar bien.", "everything", "will be", "fine"),
        ],
    ),
    (
        20,
        ("Review & A2 Mission", "Revisão e missão prática A2", "Repaso y misión práctica A2"),
        ("Review & A2 Mission — combine past, present and future in one story",
         "Revisão e Missão A2 — combine passado, presente e futuro em uma história",
         "Repaso y Misión A2 — combina pasado, presente y futuro en una historia"),
        ("Review", "A2 mission", "Telling a story"),
        [
            S("Last year I changed my job and my city.", "No ano passado mudei de emprego e de cidade.", "El año pasado cambié de trabajo y de ciudad.", "I", "changed", "my job and my city"),
            S("Next week I am going to start a new course.", "Na próxima semana vou começar um novo curso.", "La próxima semana voy a empezar un nuevo curso.", "I", "am going to start", "a new course"),
            S("I have been feeling much better recently.", "Tenho me sentido muito melhor ultimamente.", "Me he sentido mucho mejor últimamente.", "I", "have been feeling", "much better recently"),
            S("Can you tell me how to get to the station?", "Você pode me dizer como chegar à estação?", "¿Puedes decirme cómo llegar a la estación?", "you", "can tell", "me how to get to the station"),
        ],
    ),
    (
        21,
        ("Telling Stories", "Contar histórias", "Contar historias"),
        ("Telling Stories — narrate a sequence of events with detail and flow",
         "Contar Histórias — narre uma sequência de eventos com detalhe e fluidez",
         "Contar Historias — narra una secuencia de eventos con detalle y fluidez"),
        ("Storytelling", "Sequencing", "Past narration"),
        [
            S("I was walking home when I saw my old friend.", "Eu estava voltando para casa quando vi meu velho amigo.", "Caminaba a casa cuando vi a mi viejo amigo.", "I", "was walking", "home when I saw my old friend"),
            S("He told me he had moved to another city.", "Ele me contou que tinha se mudado para outra cidade.", "Me contó que se había mudado a otra ciudad.", "he", "told", "me he had moved to another city"),
            S("We talked for hours about the old days.", "Conversamos por horas sobre os velhos tempos.", "Hablamos durante horas sobre los viejos tiempos.", "we", "talked", "for hours about the old days"),
            S("I had never expected to see him again.", "Eu nunca esperei vê-lo de novo.", "Nunca esperé volver a verlo.", "I", "had expected", "to see him again"),
        ],
    ),
    (
        22,
        ("Describing Experiences", "Descrever experiências", "Describir experiencias"),
        ("Describing Experiences — share experiences using the present perfect",
         "Descrever Experiências — compartilhe experiências usando o present perfect",
         "Describir Experiencias — comparte experiencias usando el presente perfecto"),
        ("Present perfect", "Experiences", "Life events"),
        [
            S("I have never tried sushi before.", "Eu nunca experimentei sushi antes.", "Nunca he probado el sushi antes.", "I", "have tried", "sushi before"),
            S("Have you ever visited a foreign country?", "Você já visitou um país estrangeiro?", "¿Has visitado alguna vez un país extranjero?", "you", "have visited", "a foreign country"),
            S("The trip was amazing but exhausting.", "A viagem foi incrível, mas cansativa.", "El viaje fue increíble pero agotador.", "the trip", "was", "amazing but exhausting"),
            S("I have been learning English since 2020.", "Estou aprendendo inglês desde 2020.", "He estado aprendiendo inglés desde 2020.", "I", "have been learning", "English since 2020"),
        ],
    ),
    (
        23,
        ("Explaining Problems and Solutions", "Explicar problemas e soluções", "Explicar problemas y soluciones"),
        ("Explaining Problems and Solutions — describe an issue and propose a fix",
         "Explicar Problemas e Soluções — descreva um problema e proponha uma solução",
         "Explicar Problemas y Soluciones — describe un problema y propón una solución"),
        ("Problems", "Solutions", "Advice"),
        [
            S("The problem is that we don't have enough time.", "O problema é que não temos tempo suficiente.", "El problema es que no tenemos suficiente tiempo.", "the problem", "is", "that we don't have enough time"),
            S("I think we should solve this step by step.", "Acho que devemos resolver isso passo a passo.", "Creo que deberíamos resolver esto paso a paso.", "we", "should solve", "this step by step"),
            S("What would you do in my situation?", "O que você faria na minha situação?", "¿Qué harías tú en mi situación?", "you", "would do", "what in my situation"),
            S("We solved the issue by talking openly.", "Resolvemos o problema conversando abertamente.", "Resolvemos el problema hablando abiertamente.", "we", "solved", "the issue by talking openly"),
        ],
    ),
    (
        24,
        ("Expressing Opinions", "Expressar opiniões", "Expresar opiniones"),
        ("Expressing Opinions — state your point of view and back it up",
         "Expressar Opiniões — apresente seu ponto de vista e justifique",
         "Expresar Opiniones — presenta tu punto de vista y justifícalo"),
        ("Opinions", "Beliefs", "Points of view"),
        [
            S("In my opinion, online classes are very useful.", "Na minha opinião, as aulas online são muito úteis.", "En mi opinión, las clases en línea son muy útiles.", "online classes", "are", "very useful"),
            S("I believe that practice is more important than theory.", "Acredito que a prática é mais importante que a teoria.", "Creo que la práctica es más importante que la teoría.", "practice", "is", "more important than theory"),
            S("From my point of view, this plan will work.", "Do meu ponto de vista, este plano vai funcionar.", "Desde mi punto de vista, este plan va a funcionar.", "this plan", "will work", ""),
            S("What do you think about the new proposal?", "O que você acha da nova proposta?", "¿Qué opinas de la nueva propuesta?", "you", "think", "what about the new proposal"),
        ],
    ),
    (
        25,
        ("Agreeing and Disagreeing", "Concordar e discordar", "Estar de acuerdo y en desacuerdo"),
        ("Agreeing and Disagreeing — agree, disagree and soften your views",
         "Concordar e Discordar — concorde, discorde e suavize suas opiniões",
         "Estar de Acuerdo y en Desacuerdo — acepta, discrepa y suaviza tus opiniones"),
        ("Agreement", "Disagreement", "Softening"),
        [
            S("I completely agree with you.", "Concordo totalmente com você.", "Estoy completamente de acuerdo contigo.", "I", "agree", "with you"),
            S("I see your point, but I disagree.", "Entendo seu ponto de vista, mas discordo.", "Entiendo tu punto, pero no estoy de acuerdo.", "I", "disagree", "with your point"),
            S("That's a good point, however.", "Esse é um bom ponto, porém.", "Ese es un buen punto, sin embargo.", "that", "is", "a good point"),
            S("We don't have to agree on everything.", "Não precisamos concordar em tudo.", "No tenemos que estar de acuerdo en todo.", "we", "have to agree", "on everything"),
        ],
    ),
    (
        26,
        ("Suggestions and Recommendations", "Sugestões e recomendações", "Sugerencias y recomendaciones"),
        ("Suggestions and Recommendations — propose ideas and give advice",
         "Sugestões e Recomendações — proponha ideias e dê conselhos",
         "Sugerencias y Recomendaciones — propón ideas y da consejos"),
        ("Suggestions", "Recommendations", "Advice"),
        [
            S("I suggest we start the meeting at ten.", "Sugiro que comecemos a reunião às dez.", "Sugiero que empecemos la reunión a las diez.", "I", "suggest", "we start the meeting at ten"),
            S("Why don't you try a different approach?", "Por que você não tenta uma abordagem diferente?", "¿Por qué no pruebas un enfoque diferente?", "you", "try", "a different approach"),
            S("I would recommend this restaurant to everyone.", "Eu recomendaria este restaurante para todos.", "Recomendaría este restaurante a todos.", "I", "would recommend", "this restaurant to everyone"),
            S("How about going for a walk this afternoon?", "Que tal dar uma caminhada esta tarde?", "¿Qué tal dar un paseo esta tarde?", "we", "go", "for a walk this afternoon"),
        ],
    ),
    (
        27,
        ("Social Relationships", "Relacionamentos sociais", "Relaciones sociales"),
        ("Social Relationships — talk about friends, colleagues and connections",
         "Relacionamentos Sociais — fale sobre amigos, colegas e conexões",
         "Relaciones Sociales — habla de amigos, compañeros y conexiones"),
        ("Friends", "Colleagues", "Keeping in touch"),
        [
            S("I get along well with my coworkers.", "Eu me dou bem com meus colegas de trabalho.", "Me llevo bien con mis compañeros de trabajo.", "I", "get along", "with my coworkers"),
            S("We have been friends since high school.", "Somos amigos desde o ensino médio.", "Somos amigos desde la secundaria.", "we", "have been", "friends since high school"),
            S("She is the kind of person who always helps.", "Ela é o tipo de pessoa que sempre ajuda.", "Ella es el tipo de persona que siempre ayuda.", "she", "is", "the kind of person who always helps"),
            S("It's important to keep in touch with friends.", "É importante manter contato com os amigos.", "Es importante mantener el contacto con los amigos.", "it", "is", "important to keep in touch with friends"),
        ],
    ),
    (
        28,
        ("Technology and Communication", "Tecnologia e comunicação", "Tecnología y comunicación"),
        ("Technology and Communication — talk about devices, apps and online life",
         "Tecnologia e Comunicação — fale sobre aparelhos, aplicativos e vida online",
         "Tecnología y Comunicación — habla de aparatos, aplicaciones y vida en línea"),
        ("Devices", "Apps", "Online life"),
        [
            S("I can't imagine my life without the internet.", "Não consigo imaginar minha vida sem a internet.", "No puedo imaginar mi vida sin internet.", "I", "can't imagine", "my life without the internet"),
            S("The app saves all your progress automatically.", "O aplicativo salva todo o seu progresso automaticamente.", "La aplicación guarda todo tu progreso automáticamente.", "the app", "saves", "all your progress automatically"),
            S("Have you tried the new update yet?", "Você já experimentou a nova atualização?", "¿Ya probaste la nueva actualización?", "you", "have tried", "the new update"),
            S("Technology makes communication much easier.", "A tecnologia torna a comunicação muito mais fácil.", "La tecnología hace la comunicación mucho más fácil.", "technology", "makes", "communication much easier"),
        ],
    ),
    (
        29,
        ("Personal and Professional Goals", "Objetivos pessoais e profissionais", "Objetivos personales y profesionales"),
        ("Personal and Professional Goals — talk about ambitions and plans",
         "Objetivos Pessoais e Profissionais — fale sobre ambições e planos",
         "Objetivos Personales y Profesionales — habla de ambiciones y planes"),
        ("Goals", "Ambitions", "Plans"),
        [
            S("My goal is to become fluent in one year.", "Meu objetivo é ficar fluente em um ano.", "Mi objetivo es hablar con fluidez en un año.", "my goal", "is", "to become fluent in one year"),
            S("I have been saving money to start my own business.", "Tenho economizado dinheiro para abrir meu próprio negócio.", "He estado ahorrando dinero para montar mi propio negocio.", "I", "have been saving", "money to start my own business"),
            S("What are your plans for the next five years?", "Quais são seus planos para os próximos cinco anos?", "¿Cuáles son tus planes para los próximos cinco años?", "your plans", "are", "what for the next five years"),
            S("I will achieve my goals if I work hard.", "Vou alcançar meus objetivos se trabalhar duro.", "Alcanzaré mis objetivos si trabajo duro.", "I", "will achieve", "my goals if I work hard"),
        ],
    ),
    (
        30,
        ("Review & B1 Mission", "Revisão e missão prática B1", "Repaso y misión práctica B1"),
        ("Review & B1 Mission — narrate and discuss in a complete conversation",
         "Revisão e Missão B1 — narre e discuta em uma conversa completa",
         "Repaso y Misión B1 — narra y conversa en una conversación completa"),
        ("Review", "B1 mission", "Narrative"),
        [
            S("Looking back, I have learned a lot this year.", "Olhando para trás, aprendi muito este ano.", "Mirando atrás, he aprendido mucho este año.", "I", "have learned", "a lot this year"),
            S("I would like to tell you a story about my trip.", "Gostaria de contar uma história sobre minha viagem.", "Me gustaría contarte una historia sobre mi viaje.", "I", "would like to tell", "you a story about my trip"),
            S("I have just finished a difficult project.", "Acabei de terminar um projeto difícil.", "Acabo de terminar un proyecto difícil.", "I", "have finished", "a difficult project"),
            S("In conclusion, we should focus on what matters.", "Em conclusão, devemos focar no que importa.", "En conclusión, debemos centrarnos en lo que importa.", "we", "should focus", "on what matters"),
        ],
    ),
    (
        31,
        ("More Natural Conversations", "Conversas mais naturais", "Conversaciones más naturales"),
        ("More Natural Conversations — use fillers and discourse markers naturally",
         "Conversas mais Naturais — use conectivos e marcadores de fala com naturalidade",
         "Conversaciones más Naturales — usa conectores y muletillas con naturalidad"),
        ("Discourse markers", "Fillers", "Natural flow"),
        [
            S("Actually, that's not exactly what I meant.", "Na verdade, não é exatamente o que eu quis dizer.", "En realidad, no es exactamente lo que quería decir.", "that", "is", "not exactly what I meant"),
            S("To be honest, I was surprised by the result.", "Para ser honesto, fiquei surpreso com o resultado.", "Para ser honesto, me sorprendió el resultado.", "I", "was", "surprised by the result"),
            S("I mean, we could try a different way.", "Quer dizer, poderíamos tentar de outra forma.", "O sea, podríamos intentarlo de otra manera.", "we", "could try", "a different way"),
            S("By the way, have you heard the news?", "A propósito, você ouviu as notícias?", "Por cierto, ¿has oído las noticias?", "you", "have heard", "the news"),
        ],
    ),
    (
        32,
        ("News and Current Events", "Notícias e acontecimentos", "Noticias y acontecimientos"),
        ("News and Current Events — summarize and comment on what is happening",
         "Notícias e Acontecimentos — resuma e comente o que está acontecendo",
         "Noticias y Acontecimientos — resume y comenta lo que está pasando"),
        ("News", "Reports", "Current events"),
        [
            S("The government announced a new policy yesterday.", "O governo anunciou uma nova política ontem.", "El gobierno anunció una nueva política ayer.", "the government", "announced", "a new policy yesterday"),
            S("According to the report, prices are going up.", "De acordo com o relatório, os preços estão subindo.", "Según el informe, los precios están subiendo.", "prices", "are going", "up"),
            S("Thousands of people attended the event.", "Milhares de pessoas participaram do evento.", "Miles de personas asistieron al evento.", "thousands of people", "attended", "the event"),
            S("I read an article about climate change today.", "Li um artigo sobre mudanças climáticas hoje.", "Leí un artículo sobre el cambio climático hoy.", "I", "read", "an article about climate change today"),
        ],
    ),
    (
        33,
        ("Culture and Behavior", "Cultura e comportamento", "Cultura y comportamiento"),
        ("Culture and Behavior — compare customs and social expectations",
         "Cultura e Comportamento — compare costumes e expectativas sociais",
         "Cultura y Comportamiento — compara costumbres y expectativas sociales"),
        ("Customs", "Social norms", "Cultural differences"),
        [
            S("In many cultures, it is rude to be late.", "Em muitas culturas, é falta de educação chegar atrasado.", "En muchas culturas, es de mala educación llegar tarde.", "it", "is", "rude to be late"),
            S("It's common to tip in restaurants here.", "É comum dar gorjeta em restaurantes aqui.", "Es común dar propina en los restaurantes aquí.", "it", "is", "common to tip in restaurants here"),
            S("They value personal space more than we do.", "Eles valorizam o espaço pessoal mais do que nós.", "Valoran más el espacio personal que nosotros.", "they", "value", "personal space more than we do"),
            S("You should respect local customs when you travel.", "Você deve respeitar os costumes locais quando viaja.", "Debes respetar las costumbres locales cuando viajas.", "you", "should respect", "local customs when you travel"),
        ],
    ),
    (
        34,
        ("Decisions and Consequences", "Decisões e consequências", "Decisiones y consecuencias"),
        ("Decisions and Consequences — weigh options and discuss outcomes",
         "Decisões e Consequências — pese opções e discuta resultados",
         "Decisiones y Consecuencias — sopesa opciones y discute resultados"),
        ("Decisions", "Consequences", "Choices"),
        [
            S("Every decision has consequences.", "Toda decisão tem consequências.", "Toda decisión tiene consecuencias.", "every decision", "has", "consequences"),
            S("If we don't act now, it will be too late.", "Se não agirmos agora, será tarde demais.", "Si no actuamos ahora, será demasiado tarde.", "it", "will be", "too late"),
            S("She decided to move abroad for a better life.", "Ela decidiu se mudar para o exterior por uma vida melhor.", "Ella decidió mudarse al extranjero para tener una mejor vida.", "she", "decided", "to move abroad for a better life"),
            S("In hindsight, that was the right choice.", "Em retrospecto, aquela foi a escolha certa.", "En retrospectiva, esa fue la decisión correcta.", "that", "was", "the right choice"),
        ],
    ),
    (
        35,
        ("Hypotheses and Possibilities", "Hipóteses e possibilidades", "Hipótesis y posibilidades"),
        ("Hypotheses and Possibilities — imagine, speculate and soften claims",
         "Hipóteses e Possibilidades — imagine, especule e suavize afirmações",
         "Hipótesis y Posibilidades — imagina, especula y suaviza afirmaciones"),
        ("Conditionals", "Speculation", "Possibility"),
        [
            S("If I had more money, I would travel the world.", "Se eu tivesse mais dinheiro, viajaria pelo mundo.", "Si tuviera más dinero, viajaría por el mundo.", "I", "would travel", "the world"),
            S("What would you do if you won the lottery?", "O que você faria se ganhasse na loteria?", "¿Qué harías si ganaras la lotería?", "you", "would do", "what if you won the lottery"),
            S("It might rain later, so take an umbrella.", "Pode chover mais tarde, então leve um guarda-chuva.", "Puede que llueva más tarde, así que lleva un paraguas.", "it", "might rain", "later"),
            S("She may be right, but I'm not sure.", "Ela pode estar certa, mas não tenho certeza.", "Puede que ella tenga razón, pero no estoy seguro.", "she", "may be", "right"),
        ],
    ),
    (
        36,
        ("Detailed Explanations", "Explicações detalhadas", "Explicaciones detalladas"),
        ("Detailed Explanations — explain processes, reasons and conclusions",
         "Explicações Detalhadas — explique processos, razões e conclusões",
         "Explicaciones Detalladas — explica procesos, razones y conclusiones"),
        ("Explaining", "Reasons", "Conclusions"),
        [
            S("Let me explain how this works step by step.", "Deixe-me explicar como isso funciona passo a passo.", "Déjame explicar cómo funciona esto paso a paso.", "I", "explain", "how this works"),
            S("The reason we failed was lack of planning.", "A razão de termos falhado foi a falta de planejamento.", "La razón por la que fallamos fue la falta de planificación.", "the reason", "was", "lack of planning"),
            S("In other words, the system is outdated.", "Em outras palavras, o sistema está desatualizado.", "En otras palabras, el sistema está desactualizado.", "the system", "is", "outdated"),
            S("To sum up, we need more time and money.", "Para resumir, precisamos de mais tempo e dinheiro.", "En resumen, necesitamos más tiempo y dinero.", "we", "need", "more time and money"),
        ],
    ),
    (
        37,
        ("Customer Service", "Atendimento ao cliente", "Atención al cliente"),
        ("Customer Service — complain, escalate and resolve issues politely",
         "Atendimento ao Cliente — reclame, peça ajuda e resolva problemas com educação",
         "Atención al Cliente — reclama, pide ayuda y resuelve problemas con educación"),
        ("Complaints", "Refunds", "Resolving issues"),
        [
            S("I would like to make a complaint about the service.", "Gostaria de fazer uma reclamação sobre o serviço.", "Me gustaría presentar una queja sobre el servicio.", "I", "would like to make", "a complaint about the service"),
            S("Could you check the status of my order, please?", "Você pode verificar o status do meu pedido, por favor?", "¿Puede verificar el estado de mi pedido, por favor?", "you", "could check", "the status of my order"),
            S("We apologize for the inconvenience.", "Pedimos desculpas pelo transtorno.", "Nos disculpamos por las molestias.", "we", "apologize", "for the inconvenience"),
            S("I was promised a refund, but I never received it.", "Prometeram-me um reembolso, mas nunca o recebi.", "Me prometieron un reembolso, pero nunca lo recibí.", "I", "was promised", "a refund"),
        ],
    ),
    (
        38,
        ("Meetings and Teamwork", "Reuniões e trabalho em equipe", "Reuniones y trabajo en equipo"),
        ("Meetings and Teamwork — run meetings, assign tasks and collaborate",
         "Reuniões e Trabalho em Equipe — conduza reuniões, distribua tarefas e colabore",
         "Reuniones y Trabajo en Equipo — dirige reuniones, reparte tareas y colabora"),
        ("Meetings", "Teamwork", "Tasks"),
        [
            S("Could we go over the agenda before we start?", "Podemos revisar a pauta antes de começar?", "¿Podemos repasar el orden del día antes de empezar?", "we", "could go over", "the agenda before we start"),
            S("I would like to hear everyone's opinion on this.", "Gostaria de ouvir a opinião de todos sobre isso.", "Me gustaría escuchar la opinión de todos sobre esto.", "I", "would like to hear", "everyone's opinion on this"),
            S("Let's assign tasks and set a deadline.", "Vamos distribuir as tarefas e definir um prazo.", "Asignemos tareas y pongamos una fecha límite.", "we", "assign", "tasks and set a deadline"),
            S("We worked as a team to solve the problem.", "Trabalhamos em equipe para resolver o problema.", "Trabajamos en equipo para resolver el problema.", "we", "worked", "as a team to solve the problem"),
        ],
    ),
    (
        39,
        ("Professional Presentations", "Apresentações profissionais", "Presentaciones profesionales"),
        ("Professional Presentations — present results, walk through slides, answer questions",
         "Apresentações Profissionais — apresente resultados, guie slides e responda perguntas",
         "Presentaciones Profesionales — presenta resultados, guía diapositivas y responde preguntas"),
        ("Presentations", "Results", "Q&A"),
        [
            S("Today I'm going to present our quarterly results.", "Hoje vou apresentar nossos resultados trimestrais.", "Hoy voy a presentar nuestros resultados trimestrales.", "I", "am going to present", "our quarterly results"),
            S("Let me walk you through the main points.", "Deixe-me apresentar os pontos principais.", "Déjame explicarte los puntos principales.", "I", "walk", "you through the main points"),
            S("As you can see, sales have increased significantly.", "Como podem ver, as vendas aumentaram significativamente.", "Como pueden ver, las ventas han aumentado significativamente.", "sales", "have increased", "significantly"),
            S("If you have any questions, I'll be happy to answer.", "Se tiverem perguntas, ficarei feliz em responder.", "Si tienen preguntas, estaré encantado de responderlas.", "I", "will be", "happy to answer"),
        ],
    ),
    (
        40,
        ("Review & B2 Mission", "Revisão e missão prática B2", "Repaso y misión práctica B2"),
        ("Review & B2 Mission — present, explain and persuade in one task",
         "Revisão e Missão B2 — apresente, explique e convença em uma tarefa",
         "Repaso y Misión B2 — presenta, explica y convence en una tarea"),
        ("Review", "B2 mission", "Persuasion"),
        [
            S("Looking at the bigger picture, we have made real progress.", "Olhando o panorama geral, fizemos progressos reais.", "Mirando el panorama general, hemos hecho progresos reales.", "we", "have made", "real progress"),
            S("What would have happened if we had made a different choice?", "O que teria acontecido se tivéssemos feito uma escolha diferente?", "¿Qué habría pasado si hubiéramos tomado una decisión diferente?", "what", "would have happened", ""),
            S("We need to convince the client that our proposal is better.", "Precisamos convencer o cliente de que nossa proposta é melhor.", "Necesitamos convencer al cliente de que nuestra propuesta es mejor.", "we", "need to convince", "the client that our proposal is better"),
            S("To conclude, I believe the project was a success.", "Para concluir, acredito que o projeto foi um sucesso.", "Para concluir, creo que el proyecto fue un éxito.", "the project", "was", "a success"),
        ],
    ),
    (
        41,
        ("Leadership and Delegation", "Liderança e delegação", "Liderazgo y delegación"),
        ("Leadership and Delegation — lead teams, delegate and take responsibility",
         "Liderança e Delegação — lidere equipes, delegue e assuma responsabilidade",
         "Liderazgo y Delegación — lidera equipos, delega y asume responsabilidad"),
        ("Leadership", "Delegation", "Responsibility"),
        [
            S("A good leader knows how to delegate effectively.", "Um bom líder sabe delegar com eficácia.", "Un buen líder sabe delegar con eficacia.", "a good leader", "knows", "how to delegate effectively"),
            S("I need to assign this task to someone more experienced.", "Preciso atribuir essa tarefa a alguém mais experiente.", "Necesito asignar esta tarea a alguien más experimentado.", "I", "need to assign", "this task to someone more experienced"),
            S("We should empower the team to make decisions.", "Devemos capacitar a equipe para tomar decisões.", "Debemos capacitar al equipo para tomar decisiones.", "we", "should empower", "the team to make decisions"),
            S("I take full responsibility for the outcome.", "Assumo total responsabilidade pelo resultado.", "Asumo toda la responsabilidad por el resultado.", "I", "take", "full responsibility for the outcome"),
        ],
    ),
    (
        42,
        ("Negotiation", "Negociação", "Negociación"),
        ("Negotiation — propose, counter-offer and close a deal",
         "Negociação — proponha, faça contrapropostas e feche um acordo",
         "Negociación — propón, contraoferta y cierra un acuerdo"),
        ("Offers", "Counter-offers", "Closing"),
        [
            S("We can offer you a discount if you order in bulk.", "Podemos oferecer um desconto se você pedir em grande quantidade.", "Podemos ofrecerle un descuento si pide al por mayor.", "we", "can offer", "you a discount if you order in bulk"),
            S("Let's find a middle ground that works for both of us.", "Vamos encontrar um meio-termo que funcione para nós dois.", "Busquemos un punto medio que funcione para ambos.", "we", "find", "a middle ground that works for both of us"),
            S("I'm afraid we can't accept those terms.", "Receio que não possamos aceitar esses termos.", "Me temo que no podamos aceptar esos términos.", "we", "can't accept", "those terms"),
            S("If you lower the price, we will sign today.", "Se vocês baixarem o preço, assinamos hoje.", "Si bajan el precio, firmamos hoy.", "we", "will sign", "today"),
        ],
    ),
    (
        43,
        ("Conflict Resolution", "Resolução de conflitos", "Resolución de conflictos"),
        ("Conflict Resolution — de-escalate, listen and reach agreements",
         "Resolução de Conflitos — acalme, ouça e chegue a acordos",
         "Resolución de Conflictos — calma, escucha y llega a acuerdos"),
        ("De-escalation", "Listening", "Agreements"),
        [
            S("Let's talk calmly and find out what really happened.", "Vamos conversar com calma e descobrir o que realmente aconteceu.", "Hablemos con calma y averigüemos qué pasó realmente.", "we", "talk", "calmly and find out what really happened"),
            S("I understand you're upset, and I apologize.", "Entendo que você está chateado e peço desculpas.", "Entiendo que estás molesto y me disculpo.", "I", "apologize", "for upsetting you"),
            S("We need to address the issue before it gets worse.", "Precisamos resolver o problema antes que piore.", "Debemos abordar el problema antes de que empeore.", "we", "need to address", "the issue before it gets worse"),
            S("Let's agree on a solution that respects everyone.", "Vamos concordar com uma solução que respeite a todos.", "Acordemos una solución que respete a todos.", "we", "agree", "on a solution that respects everyone"),
        ],
    ),
    (
        44,
        ("Persuasion", "Persuasão", "Persuasión"),
        ("Persuasion — build a case, address doubts and win people over",
         "Persuasão — construa argumentos, responda dúvidas e conquiste as pessoas",
         "Persuasión — construye argumentos, responde dudas y convence a la gente"),
        ("Arguments", "Objections", "Winning people over"),
        [
            S("Imagine how much easier your life would be with this.", "Imagine como sua vida seria mais fácil com isso.", "Imagina cuánto más fácil sería tu vida con esto.", "your life", "would be", "how much easier"),
            S("The evidence clearly shows that this approach works.", "As evidências mostram claramente que essa abordagem funciona.", "Las pruebas muestran claramente que este enfoque funciona.", "the evidence", "shows", "that this approach works"),
            S("If you try it for one month, you won't regret it.", "Se você experimentar por um mês, não vai se arrepender.", "Si lo pruebas durante un mes, no te arrepentirás.", "you", "won't regret", "it"),
            S("Let me show you why this is worth the investment.", "Deixe-me mostrar por que vale a pena investir nisso.", "Déjame mostrarte por qué vale la pena la inversión.", "I", "show", "you why this is worth the investment"),
        ],
    ),
    (
        45,
        ("Professional Interviews", "Entrevistas profissionais", "Entrevistas profesionales"),
        ("Professional Interviews — answer, ask and sell your experience",
         "Entrevistas Profissionais — responda, pergunte e valorize sua experiência",
         "Entrevistas Profesionales — responde, pregunta y valora tu experiencia"),
        ("Interviews", "Strengths", "Career"),
        [
            S("Could you tell me a little about yourself?", "Você poderia falar um pouco sobre você?", "¿Podría hablarme un poco de usted?", "you", "could tell", "me a little about yourself"),
            S("I believe my experience makes me a strong candidate.", "Acredito que minha experiência me torna um forte candidato.", "Creo que mi experiencia me convierte en un candidato fuerte.", "my experience", "makes", "me a strong candidate"),
            S("What are your main strengths and weaknesses?", "Quais são seus principais pontos fortes e fracos?", "¿Cuáles son sus principales fortalezas y debilidades?", "your strengths and weaknesses", "are", "what"),
            S("I am looking for a position where I can grow.", "Estou procurando uma posição onde eu possa crescer.", "Busco un puesto donde pueda crecer.", "I", "am looking for", "a position where I can grow"),
        ],
    ),
    (
        46,
        ("Project Presentations", "Apresentação de projetos", "Presentación de proyectos"),
        ("Project Presentations — introduce scope, milestones and next steps",
         "Apresentação de Projetos — apresente escopo, marcos e próximos passos",
         "Presentación de Proyectos — presenta alcance, hitos y próximos pasos"),
        ("Scope", "Milestones", "Next steps"),
        [
            S("The project has three main phases.", "O projeto tem três fases principais.", "El proyecto tiene tres fases principales.", "the project", "has", "three main phases"),
            S("Our goal is to double the user base by next year.", "Nosso objetivo é dobrar a base de usuários até o próximo ano.", "Nuestro objetivo es duplicar la base de usuarios para el próximo año.", "our goal", "is", "to double the user base by next year"),
            S("We are on track to deliver on time.", "Estamos no caminho certo para entregar no prazo.", "Vamos por buen camino para entregar a tiempo.", "we", "are", "on track to deliver on time"),
            S("The next milestone is scheduled for March.", "O próximo marco está agendado para março.", "El próximo hito está programado para marzo.", "the next milestone", "is scheduled", "for March"),
        ],
    ),
    (
        47,
        ("Analyzing Results", "Análise de resultados", "Análisis de resultados"),
        ("Analyzing Results — read data, find trends and report findings",
         "Análise de Resultados — leia dados, encontre tendências e relate descobertas",
         "Análisis de Resultados — lee datos, encuentra tendencias y reporta hallazgos"),
        ("Data", "Trends", "Findings"),
        [
            S("The data suggests that our strategy is working.", "Os dados sugerem que nossa estratégia está funcionando.", "Los datos sugieren que nuestra estrategia está funcionando.", "the data", "suggests", "that our strategy is working"),
            S("There was a significant increase in engagement.", "Houve um aumento significativo no engajamento.", "Hubo un aumento significativo en la participación.", "there", "was", "a significant increase in engagement"),
            S("We need to dig deeper into the numbers.", "Precisamos analisar os números com mais profundidade.", "Necesitamos analizar los números con más profundidad.", "we", "need to dig", "deeper into the numbers"),
            S("The results exceeded our expectations.", "Os resultados superaram nossas expectativas.", "Los resultados superaron nuestras expectativas.", "the results", "exceeded", "our expectations"),
        ],
    ),
    (
        48,
        ("Intercultural Communication", "Comunicação intercultural", "Comunicación intercultural"),
        ("Intercultural Communication — work across cultures and adapt your message",
         "Comunicação Intercultural — trabalhe entre culturas e adapte sua mensagem",
         "Comunicación Intercultural — trabaja entre culturas y adapta tu mensaje"),
        ("International teams", "Cultural awareness", "Adaptation"),
        [
            S("Working with international teams has taught me a lot.", "Trabalhar com equipes internacionais me ensinou muito.", "Trabajar con equipos internacionales me ha enseñado mucho.", "working with international teams", "has taught", "me a lot"),
            S("It's important to be aware of cultural differences.", "É importante estar atento às diferenças culturais.", "Es importante ser consciente de las diferencias culturales.", "it", "is", "important to be aware of cultural differences"),
            S("We had to adapt our presentation for the local audience.", "Tivemos que adaptar nossa apresentação para o público local.", "Tuvimos que adaptar nuestra presentación para el público local.", "we", "had to adapt", "our presentation for the local audience"),
            S("A simple gesture can mean different things in different cultures.", "Um simples gesto pode significar coisas diferentes em culturas diferentes.", "Un simple gesto puede significar cosas diferentes en distintas culturas.", "a simple gesture", "can mean", "different things in different cultures"),
        ],
    ),
    (
        49,
        ("Debates and Complex Topics", "Debates e temas complexos", "Debates y temas complejos"),
        ("Debates and Complex Topics — argue with structure and nuance",
         "Debates e Temas Complexos — argumente com estrutura e nuances",
         "Debates y Temas Complejos — argumenta con estructura y matices"),
        ("Argumentation", "Counterpoints", "Nuance"),
        [
            S("That's an interesting point, but I have to disagree.", "Esse é um ponto interessante, mas tenho que discordar.", "Ese es un punto interesante, pero tengo que discrepar.", "that", "is", "an interesting point"),
            S("Let me play devil's advocate for a moment.", "Deixe-me fazer o papel de advogado do diabo por um momento.", "Déjame ser el abogado del diablo por un momento.", "I", "play", "devil's advocate for a moment"),
            S("The evidence is not as clear-cut as it seems.", "As evidências não são tão claras quanto parecem.", "Las pruebas no son tan claras como parecen.", "the evidence", "is", "not as clear-cut as it seems"),
            S("We could debate this all day without reaching an agreement.", "Poderíamos debater isso o dia todo sem chegar a um acordo.", "Podríamos debatir esto todo el día sin llegar a un acuerdo.", "we", "could debate", "this all day"),
        ],
    ),
    (
        50,
        ("Advanced Review Mission", "Revisão e missão avançada", "Repaso y misión avanzada"),
        ("Advanced Review Mission — negotiate, persuade and resolve in one mission",
         "Revisão e Missão Avançada — negocie, convença e resolva em uma missão",
         "Repaso y Misión Avanzada — negocia, convence y resuelve en una misión"),
        ("Review", "Advanced mission", "Professional English"),
        [
            S("Over the years, I have learned to negotiate with confidence.", "Ao longo dos anos, aprendi a negociar com confiança.", "Con los años, he aprendido a negociar con confianza.", "I", "have learned", "to negotiate with confidence"),
            S("The key to persuasion is understanding the other side.", "A chave da persuasão é entender o outro lado.", "La clave de la persuasión es entender al otro lado.", "the key to persuasion", "is", "understanding the other side"),
            S("I would rather solve this together than argue.", "Prefiro resolver isso juntos do que discutir.", "Prefiero resolverlo juntos antes que discutir.", "I", "would rather solve", "this together"),
            S("Looking back, every challenge made us stronger.", "Olhando para trás, cada desafio nos tornou mais fortes.", "Mirando atrás, cada desafío nos hizo más fuertes.", "every challenge", "made", "us stronger"),
        ],
    ),
    (
        51,
        ("Advanced Storytelling", "Storytelling avançado", "Narración avanzada"),
        ("Advanced Storytelling — craft rich narratives with mood and depth",
         "Storytelling Avançado — crie narrativas ricas com clima e profundidade",
         "Narración Avanzada — crea narrativas ricas con ambiente y profundidad"),
        ("Narrative craft", "Mood", "Reflection"),
        [
            S("It was a cold winter evening when everything changed.", "Era uma noite fria de inverno quando tudo mudou.", "Era una fría noche de invierno cuando todo cambió.", "everything", "changed", "that evening"),
            S("Little did I know that this moment would define my life.", "Mal sabia eu que aquele momento definiria minha vida.", "Poco sabía yo que ese momento definiría mi vida.", "this moment", "would define", "my life"),
            S("As the years went by, I began to understand why.", "Conforme os anos passavam, comecei a entender o porquê.", "A medida que pasaban los años, empecé a entender el porqué.", "I", "began to understand", "why"),
            S("In the end, the journey was more valuable than the destination.", "No final, a jornada foi mais valiosa que o destino.", "Al final, el viaje fue más valioso que el destino.", "the journey", "was", "more valuable than the destination"),
        ],
    ),
    (
        52,
        ("Humor, Irony and Intent", "Humor, ironia e intenção", "Humor, ironía e intención"),
        ("Humor, Irony and Intent — joke, read tone and mean what you say",
         "Humor, Ironia e Intenção — brinque, leia o tom e diga o que quer dizer",
         "Humor, Ironía e Intención — bromea, lee el tono y di lo que quieres"),
        ("Humor", "Irony", "Tone"),
        [
            S("You have to take life with a grain of salt.", "É preciso levar a vida com um pouco de leveza.", "Hay que tomarse la vida con un grano de sal.", "you", "have to take", "life with a grain of salt"),
            S("Oh great, another Monday — just what I needed.", "Ótimo, mais uma segunda-feira — exatamente o que eu precisava.", "Genial, otro lunes — justo lo que necesitaba.", "another Monday", "is", "just what I needed"),
            S("I was only joking, but he took it seriously.", "Eu estava só brincando, mas ele levou a sério.", "Solo estaba bromeando, pero se lo tomó en serio.", "I", "was", "only joking"),
            S("Her sarcastic remark made everyone laugh.", "O comentário sarcástico dela fez todos rirem.", "Su comentario sarcástico hizo reír a todos.", "her sarcastic remark", "made", "everyone laugh"),
        ],
    ),
    (
        53,
        ("Emotions and Abstract Language", "Emoções e linguagem abstrata", "Emociones y lenguaje abstracto"),
        ("Emotions and Abstract Language — express feelings and abstract ideas",
         "Emoções e Linguagem Abstrata — expresse sentimentos e ideias abstratas",
         "Emociones y Lenguaje Abstracto — expresa sentimientos e ideas abstractas"),
        ("Feelings", "Abstract ideas", "Empathy"),
        [
            S("I felt a mixture of excitement and fear.", "Senti uma mistura de entusiasmo e medo.", "Sentí una mezcla de emoción y miedo.", "I", "felt", "a mixture of excitement and fear"),
            S("Sometimes words are not enough to express our feelings.", "Às vezes as palavras não são suficientes para expressar nossos sentimentos.", "A veces las palabras no son suficientes para expresar nuestros sentimientos.", "words", "are", "not enough to express our feelings"),
            S("She has a rare ability to remain calm under pressure.", "Ela tem uma rara habilidade de manter a calma sob pressão.", "Ella tiene una rara habilidad para mantener la calma bajo presión.", "she", "has", "a rare ability to remain calm under pressure"),
            S("Happiness is not a destination, but a way of traveling.", "A felicidade não é um destino, mas uma forma de viajar.", "La felicidad no es un destino, sino una forma de viajar.", "happiness", "is", "not a destination but a way of traveling"),
        ],
    ),
    (
        54,
        ("Spontaneous Communication", "Comunicação espontânea", "Comunicación espontánea"),
        ("Spontaneous Communication — think on your feet and keep the flow",
         "Comunicação Espontânea — pense rápido e mantenha o fluxo",
         "Comunicación Espontánea — piensa rápido y mantén el flujo"),
        ("Quick thinking", "Hesitation", "Natural flow"),
        [
            S("Hold on, let me think about that for a second.", "Espere, deixe-me pensar nisso por um segundo.", "Espera, déjame pensar en eso un segundo.", "I", "think", "about that for a second"),
            S("It just came to my mind that we should try this.", "Acabei de pensar que deveríamos tentar isso.", "Se me acaba de ocurrir que deberíamos intentar esto.", "it", "came to", "my mind"),
            S("To be perfectly honest, I hadn't considered that.", "Para ser totalmente honesto, eu não tinha considerado isso.", "Para ser totalmente honesto, no lo había considerado.", "I", "hadn't considered", "that"),
            S("Let's see what happens — we can adjust as we go.", "Vamos ver o que acontece — podemos ajustar no caminho.", "Veamos qué pasa — podemos ajustar sobre la marcha.", "we", "can adjust", "as we go"),
        ],
    ),
    (
        55,
        ("Advanced Debates", "Debates avançados", "Debates avanzados"),
        ("Advanced Debates — challenge ideas precisely and respond to criticism",
         "Debates Avançados — questione ideias com precisão e responda a críticas",
         "Debates Avanzados — cuestiona ideas con precisión y responde a las críticas"),
        ("Precision", "Counter-arguments", "Rebuttals"),
        [
            S("That argument has a fundamental flaw.", "Esse argumento tem uma falha fundamental.", "Ese argumento tiene una falla fundamental.", "that argument", "has", "a fundamental flaw"),
            S("You're oversimplifying a very complex issue.", "Você está simplificando demais uma questão muito complexa.", "Estás simplificando demasiado un tema muy complejo.", "you", "are oversimplifying", "a very complex issue"),
            S("Let's focus on the merits of the case.", "Vamos nos concentrar nos méritos da questão.", "Centrémonos en los méritos del caso.", "we", "focus", "on the merits of the case"),
            S("I concede your point, but it doesn't change my conclusion.", "Concedo seu ponto, mas isso não muda minha conclusão.", "Concedo tu punto, pero no cambia mi conclusión.", "I", "concede", "your point"),
        ],
    ),
    (
        56,
        ("Academic Communication", "Comunicação acadêmica", "Comunicación académica"),
        ("Academic Communication — present research and discuss ideas formally",
         "Comunicação Acadêmica — apresente pesquisas e discuta ideias formalmente",
         "Comunicación Académica — presenta investigaciones y discute ideas formalmente"),
        ("Research", "Formal register", "Analysis"),
        [
            S("The study aims to examine the effects of sleep on memory.", "O estudo tem como objetivo examinar os efeitos do sono na memória.", "El estudio pretende examinar los efectos del sueño en la memoria.", "the study", "aims", "to examine the effects of sleep on memory"),
            S("According to the research, the results are significant.", "De acordo com a pesquisa, os resultados são significativos.", "Según la investigación, los resultados son significativos.", "the results", "are", "significant"),
            S("This raises an important question that requires further study.", "Isso levanta uma questão importante que exige mais estudos.", "Esto plantea una cuestión importante que requiere más estudio.", "this", "raises", "an important question"),
            S("In conclusion, the evidence supports the hypothesis.", "Em conclusão, as evidências apoiam a hipótese.", "En conclusión, las pruebas respaldan la hipótesis.", "the evidence", "supports", "the hypothesis"),
        ],
    ),
    (
        57,
        ("Executive Communication", "Comunicação executiva", "Comunicación ejecutiva"),
        ("Executive Communication — communicate strategy with clarity and authority",
         "Comunicação Executiva — comunique estratégia com clareza e autoridade",
         "Comunicación Ejecutiva — comunica estrategia con claridad y autoridad"),
        ("Strategy", "Priorities", "Decisions"),
        [
            S("I'd like to give you a quick update on the strategy.", "Gostaria de dar uma atualização rápida sobre a estratégia.", "Me gustaría darle una actualización rápida sobre la estrategia.", "I", "would like to give", "you a quick update on the strategy"),
            S("Our priority is to reduce costs without losing quality.", "Nossa prioridade é reduzir custos sem perder qualidade.", "Nuestra prioridad es reducir costos sin perder calidad.", "our priority", "is", "to reduce costs without losing quality"),
            S("Let's align our expectations before we move forward.", "Vamos alinhar nossas expectativas antes de avançar.", "Alineemos nuestras expectativas antes de avanzar.", "we", "align", "our expectations before we move forward"),
            S("The bottom line is that we need to act now.", "A questão central é que precisamos agir agora.", "El punto clave es que necesitamos actuar ahora.", "we", "need to act", "now"),
        ],
    ),
    (
        58,
        ("Unpredictable Situations", "Situações imprevisíveis", "Situaciones impredecibles"),
        ("Unpredictable Situations — stay calm, adapt and react to surprises",
         "Situações Imprevisíveis — mantenha a calma, adapte-se e reaja a imprevistos",
         "Situaciones Impredecibles — mantén la calma, adáptate y reacciona a lo inesperado"),
        ("Improvising", "Adapting", "Staying calm"),
        [
            S("You never know what's going to happen next.", "Você nunca sabe o que vai acontecer em seguida.", "Nunca sabes qué va a pasar después.", "you", "never know", "what's going to happen next"),
            S("When things go wrong, stay flexible and adapt.", "Quando as coisas dão errado, mantenha-se flexível e adapte-se.", "Cuando las cosas salen mal, mantente flexible y adáptate.", "you", "stay", "flexible and adapt"),
            S("It was a last-minute change, but we handled it well.", "Foi uma mudança de última hora, mas lidamos bem com isso.", "Fue un cambio de última hora, pero lo manejamos bien.", "we", "handled", "it well"),
            S("You can't control everything — you can only prepare.", "Você não pode controlar tudo — só pode se preparar.", "No puedes controlarlo todo — solo puedes prepararte.", "you", "can't control", "everything"),
        ],
    ),
    (
        59,
        ("Personal Fluency Project", "Projeto pessoal de fluência", "Proyecto personal de fluidez"),
        ("Personal Fluency Project — build and track your own fluency plan",
         "Projeto Pessoal de Fluência — construa e acompanhe seu próprio plano de fluência",
         "Proyecto Personal de Fluidez — construye y sigue tu propio plan de fluidez"),
        ("Fluency plan", "Habits", "Self-assessment"),
        [
            S("I am building my own plan to reach fluency.", "Estou construindo meu próprio plano para alcançar a fluência.", "Estoy construyendo mi propio plan para alcanzar la fluidez.", "I", "am building", "my own plan to reach fluency"),
            S("Speaking every day is the key to progress.", "Falar todos os dias é a chave do progresso.", "Hablar todos los días es la clave del progreso.", "speaking every day", "is", "the key to progress"),
            S("I track my mistakes and review them every week.", "Registro meus erros e os reviso toda semana.", "Registro mis errores y los reviso cada semana.", "I", "track", "my mistakes and review them every week"),
            S("Fluency is not perfection — it's confidence.", "Fluência não é perfeição — é confiança.", "La fluidez no es perfección — es confianza.", "fluency", "is", "not perfection but confidence"),
        ],
    ),
    (
        60,
        ("Final Mastery Mission", "Missão final de domínio", "Misión final de dominio"),
        ("Final Mastery Mission — reflect on the journey and speak freely",
         "Missão Final de Domínio — reflita sobre a jornada e fale livremente",
         "Misión Final de Dominio — reflexiona sobre el viaje y habla con libertad"),
        ("Final mission", "Reflection", "Fluency"),
        [
            S("Looking back at my journey, I can't believe how far I've come.", "Olhando para trás na minha jornada, não acredito o quanto evoluí.", "Mirando atrás en mi viaje, no puedo creer lo lejos que he llegado.", "I", "can't believe", "how far I've come"),
            S("I can now express myself naturally on any topic.", "Agora posso me expressar naturalmente sobre qualquer assunto.", "Ahora puedo expresarme con naturalidad sobre cualquier tema.", "I", "can express", "myself naturally on any topic"),
            S("This is not the end of the journey — it's the beginning.", "Este não é o fim da jornada — é o começo.", "Este no es el fin del viaje — es el comienzo.", "this", "is", "not the end of the journey"),
            S("Thank you for learning with me. Let's keep going.", "Obrigado por aprender comigo. Vamos continuar.", "Gracias por aprender conmigo. Sigamos adelante.", "you", "keep", "going with me"),
        ],
    ),
]

# Goals (PT) backfilled for the existing planets 1-8.
EXISTING_GOALS = {
    1: "Apresente-se e faça seus primeiros contatos em inglês",
    2: "Fale sobre sua rotina e ações do dia a dia",
    3: "Peça ajuda, combine horários e resolva problemas",
    4: "Peça comida, cozinhe e faça compras",
    5: "Pergunte direções e viaje com confiança",
    6: "Fale sobre saúde, corpo e emoções",
    7: "Conduza reuniões, e-mails e ligações profissionais",
    8: "Dê opiniões, conte histórias e use expressões naturais",
}

# Standard 10-block path shared by every planet (spec "Estrutura padrão dos 10 blocos").
BLOCKS = [
    (1, "context", "Context & Diagnosis", "Meet the theme in a real situation and show what you already know"),
    (2, "vocabulary", "Essential Vocabulary", "Learn only the words and expressions you really need"),
    (3, "phrases", "Fundamental Phrases", "Master the key sentences of this planet"),
    (4, "structure", "Sentence Building", "Build sentences: subject, verb, complement, time and place"),
    (5, "listening", "Listening Comprehension", "Understand phrases and dialogues spoken naturally"),
    (6, "pronunciation", "Pronunciation & Shadowing", "Listen and repeat — clarity, rhythm and intonation"),
    (7, "recall", "Active Recall", "Produce the language from memory, without copying"),
    (8, "variations", "Variations & Transformations", "Turn statements into questions, past into future, and more"),
    (9, "conversation", "Practical Conversation", "Have a real conversation using what you learned"),
    (10, "mission", "Planet Mission", "Use everything together and conquer the planet"),
]
