#!/usr/bin/env python3
"""Generate the 60-planet curriculum migration from scripts/curriculum_data.py.

Writes backend/migrations/2026-08-12-000002_sixty_planets/{up,down}.sql.

Course layout (six base→target pairs, each with its own planet set):
  (pt,en)  prefix ''   (base pt, target en) — the flagship English course
  (pt,es)  prefix 'e'  (base pt, target es)
  (en,pt)  prefix 'f'  (base en, target pt)
  (es,en)  prefix 'a'  (base es, target en)
  (en,es)  prefix 'b'  (base en, target es)
  (es,pt)  prefix 'c'  (base es, target pt)

Planet ids are deterministic: for planet N and course prefix P the uuid is
(P + NNNNNNN | NNNNNNNN)-NNNN-4NNN-8NNN-NNNNNNNNNNNN (zero-padded), which
continues the existing id style without colliding for N >= 9.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from curriculum_data import BLOCKS, EXISTING_GOALS, PLANETS  # noqa: E402

MIGRATION_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "backend",
    "migrations",
    "2026-08-12-000002_sixty_planets",
)

# (prefix, base_language, target_language, subtitle_index, target_name_pt, target_name_es)
COURSES = [
    ("", "pt", "en", 1, "inglês", "inglés"),
    ("e", "pt", "es", 1, "espanhol", "español"),
    ("f", "en", "pt", 0, "inglês", "inglés"),
    ("a", "es", "en", 2, "inglês", "inglés"),
    ("b", "en", "es", 0, "espanhol", "español"),
    ("c", "es", "pt", 2, "inglês", "inglés"),
]

PALETTE = [
    "#7C6FF0", "#5BB4A4", "#E08A3C", "#B48AD9", "#3E9E8F", "#D16BA5",
    "#6A9BD9", "#C9A227", "#E2574C", "#4A90D9", "#E8B64C", "#6FC7C9",
]

# Sentence column mapping per course: (target_col, base_col, unused_col)
SENTENCE_COLS = {
    ("pt", "en"): ("en", "pt", "es"),
    ("pt", "es"): ("es", "pt", "en"),
    ("en", "pt"): ("pt", "en", "es"),
    ("es", "en"): ("en", "es", "pt"),
    ("en", "es"): ("es", "en", "pt"),
    ("es", "pt"): ("pt", "es", "en"),
}

LANG_TITLE = {"en": 0, "pt": 1, "es": 2}
LANG_SUB = {"en": 0, "pt": 1, "es": 2}


def planet_id(prefix, number):
    if prefix:
        group1 = prefix + "{:07d}".format(number)
    else:
        group1 = "{:08d}".format(number)
    return "{}-{:04d}-4{:03d}-8{:03d}-{:012d}".format(
        group1, number, number, number, number
    )


def level_for(number):
    if number <= 10:
        return "A1"
    if number <= 20:
        return "A2"
    if number <= 30:
        return "B1"
    if number <= 40:
        return "B2"
    if number <= 50:
        return "B2+"
    return "C1"


def goal_for(number):
    if number <= 8:
        return EXISTING_GOALS[number]
    for planet in PLANETS:
        if planet[0] == number:
            pt_sub = planet[2][1]
            return pt_sub.split(" — ", 1)[1].strip() if " — " in pt_sub else pt_sub
    raise ValueError(f"missing goal for planet {number}")


def sql(s):
    return s.replace("'", "''")


def color_for(number):
    return PALETTE[(number - 9) % len(PALETTE)]


def planet_row(planet, base_lang, target_lang):
    number, titles, subs, topics, _ = planet
    color = color_for(number)
    title = titles[LANG_TITLE[base_lang]]
    sub = subs[LANG_SUB[base_lang]]
    topics_json = json.dumps(list(topics), ensure_ascii=False)
    return (
        number,
        title,
        sub,
        color,
        topics_json,
        base_lang,
        target_lang,
    )


def build_up():
    lines = []
    w = lines.append
    w("-- ---------------------------------------------------------------------------")
    w("-- Hupy 60-planet curriculum (generated by scripts/generate-curriculum.py).")
    w("--")
    w("-- Expands the course from 8 planets to the full 60-planet journey (6 phases,")
    w("-- A1 -> C1), converts every planet to the standard 10-block path, seeds key")
    w("-- sentences and scripted lesson steps for the new planets — for all six")
    w("-- base->target courses. Regenerate with:  python3 scripts/generate-curriculum.py")
    w("-- ---------------------------------------------------------------------------")
    w("")
    w("-- 1. Planet metadata: level (A1..C1) + communication goal")
    w("ALTER TABLE planets ADD COLUMN level VARCHAR(8) NOT NULL DEFAULT 'A1';")
    w("ALTER TABLE planets ADD COLUMN goal TEXT NOT NULL DEFAULT '';")
    w("")
    w("UPDATE planets SET level = CASE")
    w("    WHEN number <= 10 THEN 'A1'")
    w("    WHEN number <= 20 THEN 'A2'")
    w("    WHEN number <= 30 THEN 'B1'")
    w("    WHEN number <= 40 THEN 'B2'")
    w("    WHEN number <= 50 THEN 'B2+'")
    w("    ELSE 'C1'")
    w("END;")
    w("")
    for number, goal in sorted(EXISTING_GOALS.items()):
        w("UPDATE planets SET goal = '{}' WHERE number = {};".format(sql(goal), number))
    w("")
    w("-- 2. New planets (9-60) for all six courses")
    w("INSERT INTO planets (id, number, title, subtitle, color, topics, unlock_mastery, language, base_language, level, goal) VALUES")
    rows = []
    for planet in PLANETS:
        number, titles, subs, _, _ = planet
        goal = goal_for(number)
        level = level_for(number)
        for prefix, base_lang, target_lang, *_ in COURSES:
            _, title, sub, color, topics_json, _, _ = planet_row(planet, base_lang, target_lang)
            rows.append(
                "('{}', {}, '{}', '{}', '{}', '{}'::jsonb, 0.8, '{}', '{}', '{}', '{}')".format(
                    planet_id(prefix, number), number, sql(title), sql(sub), color,
                    topics_json, target_lang, base_lang, level, sql(goal),
                )
            )
    w(",\n".join(rows) + ";")
    w("")
    w("-- 3. Blocks: convert every planet to the standard 10-block path")
    w("-- The old rows are removed first so the tightened kind check cannot")
    w("-- be violated by the legacy 4-kind path.")
    w("DELETE FROM planet_lessons;")
    w("")
    w("DO $$ BEGIN")
    w("    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'planet_lessons_kind_check') THEN")
    w("        ALTER TABLE planet_lessons DROP CONSTRAINT planet_lessons_kind_check;")
    w("    END IF;")
    w("END $$;")
    kinds = ", ".join("'{}'".format(k) for _, k, _, _ in BLOCKS)
    w("ALTER TABLE planet_lessons ADD CONSTRAINT planet_lessons_kind_check CHECK (kind IN ({}));".format(kinds))
    w("")
    w("INSERT INTO planet_lessons (planet_id, position, kind, title, description)")
    w("SELECT p.id, b.position, b.kind, b.title, b.description")
    w("FROM planets p")
    w("CROSS JOIN (VALUES")
    block_rows = [
        "    ({}, '{}', '{}', '{}')".format(pos, kind, sql(title), sql(desc))
        for pos, kind, title, desc in BLOCKS
    ]
    w(",\n".join(block_rows))
    w(") AS b(position, kind, title, description)")
    w("ORDER BY p.number, b.position;")
    w("")
    w("-- 4. Key sentences for the new planets (all six courses)")
    w("INSERT INTO planet_sentences (planet_id, position, en, pt, es, subject, verb, complement) VALUES")
    sentence_rows = []
    for planet in PLANETS:
        number, _, _, _, sentences = planet
        for pos, (en, pt, es, subject, verb, complement) in enumerate(sentences, start=1):
            for prefix, base_lang, target_lang, *_ in COURSES:
                tgt, base, unused = SENTENCE_COLS[(base_lang, target_lang)]
                texts = {"en": en, "pt": pt, "es": es}
                target_text = texts[tgt]
                base_text = texts[base]
                # The unused slot stays empty, matching the existing courses.
                unused_text = ""
                sentence_rows.append(
                    "('{}', {}, '{}', '{}', '{}', '{}', '{}', '{}')".format(
                        planet_id(prefix, number), pos, sql(target_text), sql(base_text),
                        sql(unused_text), sql(subject), sql(verb), sql(complement),
                    )
                )
    w(",\n".join(sentence_rows) + ";")
    w("")
    w("-- 5. Scripted lesson steps for the new planets (all six courses)")
    w("INSERT INTO lesson_steps")
    w("    (planet_id, position, kind, tutor_text, expected_text, mastery_gain)")
    w("VALUES")
    step_rows = []
    for planet in PLANETS:
        number, _, _, _, sentences = planet
        for prefix, base_lang, target_lang, sub_idx, target_name_pt, target_name_es in COURSES:
            tgt, base, _ = SENTENCE_COLS[(base_lang, target_lang)]
            s1 = sentences[0]
            s2 = sentences[1]
            t1, b1 = s1[{"en": 0, "pt": 1, "es": 2}[tgt]], s1[{"en": 0, "pt": 1, "es": 2}[base]]
            t2 = s2[{"en": 0, "pt": 1, "es": 2}[tgt]]
            b2 = s2[{"en": 0, "pt": 1, "es": 2}[base]]
            pid = planet_id(prefix, number)
            if base_lang == "pt":
                target_name = target_name_pt
                teach = 'Sergio, "{}" em {} é "{}". Listen: {}. Agora repita.'.format(b1, target_name, t1, t1)
                repeat = "Muito bem! Diga de novo, com ritmo natural."
                question = 'Como se diz "{}" em {}?'.format(b2, target_name)
                praise = "Excelente! Você está pronto para o próximo passo."
            elif base_lang == "es":
                target_name = target_name_es
                teach = 'Sergio, "{}" en {} es "{}". Escucha: {}. Ahora repite.'.format(b1, target_name, t1, t1)
                repeat = "¡Muy bien! Dilo otra vez, con ritmo natural."
                question = '¿Cómo se dice "{}" en {}?'.format(b2, target_name)
                praise = "¡Excelente! Estás listo para el siguiente paso."
            else:
                target_name = {"en": "English", "pt": "Portuguese", "es": "Spanish"}[target_lang]
                teach = 'Sergio, "{}" in {} is "{}". Listen: {}. Now repeat.'.format(b1, target_name, t1, t1)
                repeat = "Very good! Say it again with a natural rhythm."
                question = 'How do you say "{}" in {}?'.format(b2, target_name)
                praise = "Excellent! You are ready for the next step."
            step_rows.append(
                "('{}', 1, 'teach', '{}', '{}', 0.06)".format(pid, sql(teach), sql(t1))
            )
            step_rows.append(
                "('{}', 2, 'repeat', '{}', '{}', NULL)".format(pid, sql(repeat), sql(t1))
            )
            step_rows.append(
                "('{}', 3, 'question', '{}', '{}', NULL)".format(pid, sql(question), sql(t2))
            )
            step_rows.append(
                "('{}', 4, 'praise', '{}', NULL, 0.05)".format(pid, sql(praise))
            )
    w(",\n".join(step_rows) + ";")
    w("")
    return "\n".join(lines)


def build_down():
    lines = []
    w = lines.append
    w("-- Revert the 60-planet curriculum (generated by scripts/generate-curriculum.py).")
    w("")
    w("DELETE FROM lesson_steps WHERE planet_id IN (SELECT id FROM planets WHERE number >= 9);")
    w("")
    w("DELETE FROM planet_sentences WHERE planet_id IN (SELECT id FROM planets WHERE number >= 9);")
    w("")
    w("-- The 10-block path replaces the old 4-lesson path; the original custom titles")
    w("-- are not restorable, so the down migration simply removes the new blocks.")
    w("DO $$ BEGIN")
    w("    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'planet_lessons_kind_check') THEN")
    w("        ALTER TABLE planet_lessons DROP CONSTRAINT planet_lessons_kind_check;")
    w("    END IF;")
    w("END $$;")
    w("ALTER TABLE planet_lessons ADD CONSTRAINT planet_lessons_kind_check CHECK (kind IN ('learn', 'practice', 'test', 'master'));")
    w("")
    w("DELETE FROM planet_lessons WHERE kind NOT IN ('learn', 'practice', 'test', 'master');")
    w("")
    w("DELETE FROM planets WHERE number >= 9;")
    w("")
    w("ALTER TABLE planets DROP COLUMN goal;")
    w("ALTER TABLE planets DROP COLUMN level;")
    w("")
    return "\n".join(lines)


def main():
    os.makedirs(MIGRATION_DIR, exist_ok=True)
    with open(os.path.join(MIGRATION_DIR, "up.sql"), "w") as f:
        f.write(build_up() + "\n")
    with open(os.path.join(MIGRATION_DIR, "down.sql"), "w") as f:
        f.write(build_down() + "\n")
    print("wrote", MIGRATION_DIR)


if __name__ == "__main__":
    main()
