-- Revert the 60-planet curriculum (generated by scripts/generate-curriculum.py).

DELETE FROM lesson_steps WHERE planet_id IN (SELECT id FROM planets WHERE number >= 9);

DELETE FROM planet_sentences WHERE planet_id IN (SELECT id FROM planets WHERE number >= 9);

-- The 10-block path replaces the old 4-lesson path; the original custom titles
-- are not restorable, so the down migration simply removes the new blocks.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'planet_lessons_kind_check') THEN
        ALTER TABLE planet_lessons DROP CONSTRAINT planet_lessons_kind_check;
    END IF;
END $$;
ALTER TABLE planet_lessons ADD CONSTRAINT planet_lessons_kind_check CHECK (kind IN ('learn', 'practice', 'test', 'master'));

DELETE FROM planet_lessons WHERE kind NOT IN ('learn', 'practice', 'test', 'master');

DELETE FROM planets WHERE number >= 9;

ALTER TABLE planets DROP COLUMN goal;
ALTER TABLE planets DROP COLUMN level;

